### ISSUE TITLE
Co-op LEDs button should be a while held? 

### ISSUE THREAD

**Issue by AngelaKimmy** [FRCTeam3255/2024_Robot_Code#160]
What do you think @ACat701 ?

**Comment by alicekuznetsov** [comment]
I like it staying after being hit once because the entire point is for the human player to see the lights and you don't know when they've seen it. The lights will get overridden by other LED commands later anyway. I don't see a reason in turning them off early when it's difficult for the drive team to know when the co-op button has been pressed.

In all likelihood, the actual strat is just going to be "hit the co-op button as soon as you can" anyway

**Comment by ACat701** [comment]
It'll get overridden later anyway
