### ISSUE TITLE
Note Shuffling (4414 / 254 Style)

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Robot_Code#217]
973 style shuffling notes

**Comment by alicekuznetsov** [comment]
Do we want 973-style shuffling notes? Or do we want 4414-style? (Chucking them over the stage)
We could have this + a preset that is the 4414 style yeet

**Comment by alicekuznetsov** [comment]
Related to #237

**Comment by alicekuznetsov** [comment]
Implementation:
Add a new LOCKED LOCATION. The turret should lock onto a spot in front of the speaker while the pitch would probably just be set to a preset angle. This would need to be a locked location so that the turret aims in front of the speaker no matter our rotation (we want this to be very fast to use)

**Comment by alicekuznetsov** [comment]
Swapping this to low priority because i felt like it (i actually really want this)

**Comment by alicekuznetsov** [comment]
https://youtu.be/fG3GZPQaWVE?si=5Y893IEzY_8o-ifv&t=26
