### ISSUE TITLE
LEDs are flickering in disable

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Robot_Code#220]

**Comment by AlenaNguyen** [comment]
I think this is because I call clearAnimation() at the start of setAutoPlacementLEDs, so everytime it loops, the LEDs will flicker between off and our desired color.
I did find a problem if we just get rid of clearAnimation: if we are lined up, the entire LED strip will light up orange, but then if we are misaligned again, the CANdle changes (dat's good), but the rest of the LEDs will stay orange (dat's not ideal). 
Possible solution: We could make a method to clear a certain chunk of LEDs instead of all of them
