### ISSUE TITLE
Special code for tuning preset on field

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Robot_Code#266]

**Comment by alicekuznetsov** [comment]
This code is extremely important to have for a practice match so that we can tune all of our presets. Ideally, we can test this on Wednesday very very briefly

- Log the current preset, it's angles, and it's flywheel speeds **to SmartDashboard (not Glass)**
- For this code, the preset values need to be stored as doubles, not preferences, so that we can modify them as the code runs
- 2 Buttons to make the pitch angle go up/down (by 1 degree?)
- 2 Buttons to make the turret angle go left/right (by 1 degree?)
- 2 buttons to make the flywheel speed go faster/slower  (by 5 rotations?)
No need to worry about storing the values; we have logs for these things
