### ISSUE TITLE
Add transfer game piece check if transfer roller encoder counts to determine if game piece shot

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Robot_Code#270]

**Comment by alicekuznetsov** [comment]
I'm fine with adding this for auto, but I don't want to change the implementation of the shoot command in tele-op because we are confident that it works. We can write the method in Transfer and have the auto run TransferGamePiece until it's true, but I don't want TransferGamePiece to have an isFinished
