### ISSUE TITLE
Potential Drivetrain Vision Error

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Robot_Code#280]
https://github.com/FRCTeam3255/2024_Robot_Code/blob/f7a345f80529aee1af39ea074f42d22735cb98e9/src/main/java/frc/robot/subsystems/Drivetrain.java#L87-L94

https://github.com/FRCTeam3255/2024_Robot_Code/blob/f7a345f80529aee1af39ea074f42d22735cb98e9/src/main/java/frc/robot/RobotPreferences.java#L200-L217

I believe these are being saved as meters when they are then being converted to feet in these lines

**Comment by TaylerUva** [comment]
@ACat701 would this be the source of the vision issues we were seeing?

**Comment by alicekuznetsov** [comment]
No, the issue was in the pose that was returned by the Photonvision pose estimator. The pose that was being given to the pose estimator was wrong, so the standard deviations won't have any effect on that

I definitely did forget to remove the unit conversion though! I need to go check the units on all of our javadocs haha
